//! The dictation pipeline of `scripts/dictate.sh`, in Rust, for the Windows app (docs/plans/M8-windows.md): under Git
//! Bash the script costs ~2 s per dictation, and a native `claude.exe` can't read its fifo.
//!
//! **`dictate.sh` is the specification.** Each function names the shell function it follows, and the golden tests
//! (`golden/`, generated by running the script's own functions) hold the two equal. The `ovt` binary has the script's
//! app contract (`refine`, `command`, `transcribe`: the same `VTT_*` variables, exit codes and result file), so
//! `scripts/test-dictate.sh` and `evals/run.py` run against both.

#![allow(unused_variables)] // W0 skeleton: removed when every module is filled in

pub mod claude;
pub mod config;
pub mod online;
pub mod openai;
pub mod refine;
pub mod s1;
pub mod text;
pub mod whisper;
